rm Master.aux
rm Master.bbl
rm Master.bcf
rm Master.blg
rm Master.log
rm Master.pdf
rm Master.run.xml
rm Master.ttt
xelatex Master.tex
biber Master
xelatex Master.tex
xelatex Master.tex
xelatex Master.tex
